openapi: 3.0.0

info:
  title: SmartTour Service API
  description: API description.
  version: 1.0.0

servers:
  - url: 'https://yourtrip.qbank.pro/api'
    description: Common host.
  - url: 'http://localhost:80/api'
    description: Local-dev backend.

paths:
  /locations/all:
    get:
      tags: [ locations ]
      summary: Location information.

      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /locations/get_by_params:
    post:
      tags: [ locations ]
      summary: Location filtration by parameters.
      requestBody:
        description: Filter parameters.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                budget:
                  type: array
                  items:
                    type: integer
                date:
                  type: string
                categories:
                  type: array
                  items:
                    type: string
                tags:
                  type: array
                  items:
                    type: string

            example:
              budget: [2000, 3000]
              date: "2021-06-19"

      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /categories/all:
    get:
      tags: [ categories ]
      summary: Categories information.

      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /users/all:
    get:
      tags: [ users ]
      summary: User information.

      responses:
        '200':
          description: Ok.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /hello/hey:
    get:
      tags: [ hello ]
      summary: Say hello.
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
          example: "Steve"

      responses:
        '200':
          description: Ok.
          content:
            text/plain:
              schema:
                type: string
                example: Hello Steve!
